name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        emacs_version:
          - 26.3
          - snapshot
    steps:
      - name: Setup emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Emacs version
        run: |
          echo `which emacs`
          emacs --version
