name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        emacs_version:
          - 26.3
          - snapshot
    steps:
      - name: Set up emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Output emacs version
        run: |
          emacs --version
      - name: Set up cask
        uses: cask/setup-cask@master
        with:
          version: 0.8.4
      - name: Output cask version
        run: |
          cask --version
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install all packages specified in the Cask-file
        run: |
          cask install
      - name: Run tests
        run: |
          make test
